// 8 templates pré-remplis par secteur. Click-and-go pour les nouveaux utilisateurs.

export const TEMPLATES = [
  {
    id: "boulangerie",
    icon: "🥖",
    label: "Boulangerie / Pâtisserie",
    color: "#f59e0b",
    template: {
      name: "Boulangerie [Votre nom]",
      sector: "Restauration & commerce",
      description: "Boulangerie artisanale, pains au levain et pâtisseries faites maison chaque matin.",
      services: "Pains traditionnels et spéciaux, viennoiseries, pâtisseries, sandwichs et formules midi, plateaux et gâteaux sur commande, café à emporter.",
      hours: "Mar-Sam 6h30-19h30, Dim 7h-13h, fermé le lundi",
      tone: "chaleureux",
    },
    faqs: [
      { question: "Quels sont vos horaires d'ouverture ?", answer: "Du mardi au samedi de 6h30 à 19h30, et le dimanche de 7h à 13h. Nous sommes fermés le lundi." },
      { question: "Faites-vous des commandes pour événements ?", answer: "Oui, plateaux salés et sucrés sur commande avec 48h de préavis. À partir de 12 personnes." },
      { question: "Avez-vous des pains sans gluten ?", answer: "Oui, nous proposons un pain sans gluten les mercredis et samedis, sur réservation la veille." },
      { question: "Acceptez-vous les tickets restaurant ?", answer: "Oui, nous acceptons les tickets restaurant papier et les cartes Swile, Edenred et Up." },
      { question: "Faites-vous des gâteaux d'anniversaire ?", answer: "Oui, sur commande avec 72h de préavis. Comptez 30 à 60 € selon la taille et le décor." },
      { question: "Avez-vous des allergènes ?", answer: "Beaucoup de nos produits contiennent du lait, des œufs ou des fruits à coque. Précisez votre allergie en boutique." },
    ],
  },
  {
    id: "restaurant",
    icon: "🍽️",
    label: "Restaurant / Bistrot",
    color: "#ef4444",
    template: {
      name: "Restaurant [Votre nom]",
      sector: "Restauration & commerce",
      description: "Restaurant convivial, cuisine de saison faite maison, terrasse ombragée l'été.",
      services: "Service midi et soir, menu déjeuner, carte du soir, traiteur, privatisation salle, plats à emporter.",
      hours: "Mar-Sam 12h-14h30 et 19h-22h30, fermé dim-lun",
      tone: "chaleureux",
    },
    faqs: [
      { question: "Comment réserver une table ?", answer: "Par téléphone aux horaires d'ouverture ou via notre lien Calendly. Pour les groupes de plus de 6 personnes, réservation conseillée 48h à l'avance." },
      { question: "Avez-vous une terrasse ?", answer: "Oui, terrasse ombragée de 30 couverts, accessible d'avril à octobre." },
      { question: "Faites-vous le service du midi ?", answer: "Oui, du mardi au samedi de 12h à 14h30, avec une formule à 18€ entrée-plat ou plat-dessert." },
      { question: "Avez-vous des plats végétariens ou véganes ?", answer: "Oui, nous proposons toujours au moins 2 plats végétariens et 1 plat végane à la carte." },
      { question: "Peut-on privatiser la salle ?", answer: "Oui, possibilité de privatiser pour 25 à 50 personnes. Devis sur demande." },
      { question: "Acceptez-vous les chèques restaurant ?", answer: "Oui, tickets papier et cartes Swile, Edenred, Up acceptés." },
    ],
  },
  {
    id: "medical",
    icon: "🏥",
    label: "Cabinet médical / Santé",
    color: "#06b6d4",
    template: {
      name: "Cabinet du Dr [Votre nom]",
      sector: "Santé",
      description: "Cabinet médical, consultations sur rendez-vous, urgences traitées le jour même.",
      services: "Consultations généralistes et spécialisées, suivi patients, vaccinations, certificats médicaux, télémédecine.",
      hours: "Lun-Ven 8h-19h, Sam 9h-13h, urgences sur appel",
      tone: "formel",
    },
    faqs: [
      { question: "Comment prendre rendez-vous ?", answer: "Par téléphone aux horaires d'ouverture ou via Doctolib. Délai habituel : 3 à 7 jours en consultation, urgences traitées le jour même." },
      { question: "Quels sont vos tarifs ?", answer: "Consultation 30 €, conventionné secteur 1. Tiers payant accepté avec carte vitale et mutuelle." },
      { question: "Acceptez-vous la carte vitale ?", answer: "Oui, télétransmission directe avec la carte vitale et la mutuelle." },
      { question: "Faites-vous de la téléconsultation ?", answer: "Oui, téléconsultation via Doctolib, mêmes tarifs qu'en cabinet." },
      { question: "Que faire en cas d'urgence ?", answer: "Pour une urgence vitale, appelez le 15. Pour une urgence non vitale aux horaires d'ouverture, appelez-nous, nous trouvons un créneau dans la journée." },
      { question: "Êtes-vous accessible aux PMR ?", answer: "Oui, cabinet en rez-de-chaussée accessible aux personnes à mobilité réduite." },
    ],
  },
  {
    id: "garage",
    icon: "🚗",
    label: "Garage / Auto",
    color: "#a855f7",
    template: {
      name: "Garage [Votre nom]",
      sector: "Services automobiles",
      description: "Garage multimarques, entretien, réparation, contrôle technique. Devis gratuits.",
      services: "Vidange, freins, pneus, embrayage, diagnostic électronique, pré-contrôle technique, dépannage 7j/7.",
      hours: "Lun-Ven 8h-18h, Sam 9h-13h",
      tone: "direct",
    },
    faqs: [
      { question: "Combien coûte une vidange ?", answer: "À partir de 79 € TTC main d'œuvre + huile, selon le modèle. Devis gratuit en 5 minutes par téléphone." },
      { question: "Faites-vous le pré-contrôle technique ?", answer: "Oui, pré-contrôle gratuit si vous prenez le rendez-vous chez nous pour les réparations éventuelles." },
      { question: "Faites-vous le dépannage ?", answer: "Oui, dépannage 7j/7 dans un rayon de 30 km. Forfait à partir de 65 € + kilométrage." },
      { question: "Quels délais pour une réparation ?", answer: "Petites interventions : sous 24-48h. Réparations lourdes : 3-7 jours selon disponibilité pièces." },
      { question: "Acceptez-vous tous les véhicules ?", answer: "Toutes marques européennes, japonaises, coréennes. Pour véhicules américains ou luxe, nous consulter." },
      { question: "Faites-vous le changement de pneus ?", answer: "Oui, montage + équilibrage à partir de 25 € par pneu. Pneus toutes saisons en stock." },
    ],
  },
  {
    id: "coiffure",
    icon: "💇",
    label: "Salon de coiffure / Beauté",
    color: "#ec4899",
    template: {
      name: "Salon [Votre nom]",
      sector: "Beauté & Bien-être",
      description: "Salon de coiffure mixte, coupes, couleurs, soins et coiffures événementielles.",
      services: "Coupe femme/homme/enfant, couleur, mèches, balayage, brushing, soin profond, coiffure mariage.",
      hours: "Mar-Sam 9h-19h, dim sur rendez-vous",
      tone: "chaleureux",
    },
    faqs: [
      { question: "Comment prendre rendez-vous ?", answer: "Par téléphone aux horaires d'ouverture, ou via Planity. Délai habituel : 1 à 2 semaines." },
      { question: "Quels sont vos tarifs ?", answer: "Coupe femme à partir de 35 €, homme 22 €, enfant 18 €. Couleur à partir de 55 €. Mèches/balayage à partir de 90 €." },
      { question: "Faites-vous les coiffures de mariage ?", answer: "Oui, coiffure mariage à partir de 80 €. Essai conseillé 1 mois avant. Possibilité de venir à domicile sur le secteur." },
      { question: "Acceptez-vous les enfants ?", answer: "Bien sûr, coupe enfant à partir de 18 €. Coin enfant avec jeux dans le salon." },
      { question: "Faites-vous des soins capillaires profonds ?", answer: "Oui, soins Olaplex et Kerastase à partir de 25 €. Particulièrement recommandés après une coloration." },
      { question: "Vendez-vous des produits ?", answer: "Oui, gamme professionnelle Kerastase, L'Oréal, Olaplex. Conseil personnalisé selon votre type de cheveux." },
    ],
  },
  {
    id: "immobilier",
    icon: "🏠",
    label: "Agence immobilière",
    color: "#10b981",
    template: {
      name: "Agence [Votre nom]",
      sector: "Immobilier",
      description: "Agence immobilière de proximité, transaction et location, estimation gratuite.",
      services: "Vente et achat immobilier, location, estimation gratuite, gestion locative, conseil investissement.",
      hours: "Lun-Ven 9h-12h et 14h-19h, Sam 9h30-17h",
      tone: "formel",
    },
    faqs: [
      { question: "Faites-vous des estimations gratuites ?", answer: "Oui, estimation gratuite et sans engagement, en agence ou à domicile sous 48h." },
      { question: "Quels sont vos frais d'agence ?", answer: "Vente : 4-5% TTC selon le prix du bien, à la charge de l'acquéreur. Location : 1 mois de loyer hors charges." },
      { question: "Gérez-vous la location pour les propriétaires ?", answer: "Oui, gestion locative complète à 7% TTC des loyers + assurance impayés en option." },
      { question: "Avez-vous des biens à vendre actuellement ?", answer: "Oui, environ 40 biens en portefeuille. Précisez votre recherche, je vous transfère à un négociateur dès demain." },
      { question: "Avez-vous des biens à louer ?", answer: "Oui, en moyenne 15 biens disponibles. Studios, T2, T3, T4, maisons. Décrivez-moi votre besoin." },
      { question: "Faites-vous des visites le samedi ?", answer: "Oui, visites le samedi de 9h30 à 17h, sur rendez-vous. Idéal pour les visiteurs qui travaillent en semaine." },
    ],
  },
  {
    id: "hotel",
    icon: "🏨",
    label: "Hôtel / Chambres d'hôtes",
    color: "#3b82f6",
    template: {
      name: "Hôtel [Votre nom]",
      sector: "Hôtellerie & Tourisme",
      description: "Hôtel familial, chambres confortables, petit-déjeuner inclus, parking privé.",
      services: "Chambres simples, doubles, familiales, suite, petit-déjeuner buffet, parking, Wi-Fi, salle de réunion.",
      hours: "Réception 24h/24",
      tone: "chaleureux",
    },
    faqs: [
      { question: "Avez-vous des chambres disponibles ce week-end ?", answer: "Je vérifie ça pour vous. Pouvez-vous me donner les dates précises et le nombre de personnes ?" },
      { question: "Quels sont vos tarifs ?", answer: "Chambres à partir de 79 €/nuit en simple, 95 €/nuit en double, petit-déjeuner inclus." },
      { question: "Acceptez-vous les animaux ?", answer: "Oui, animaux de moins de 10 kg acceptés moyennant 10 €/nuit. Précisez à la réservation." },
      { question: "Avez-vous un parking ?", answer: "Oui, parking privé fermé, gratuit pour les clients de l'hôtel." },
      { question: "Le petit-déjeuner est-il inclus ?", answer: "Oui, petit-déjeuner buffet servi de 7h à 10h, inclus dans toutes nos chambres." },
      { question: "Avez-vous une salle de réunion ?", answer: "Oui, salle modulable jusqu'à 30 personnes, à partir de 250 €/jour incluant pauses café." },
    ],
  },
  {
    id: "avocat",
    icon: "⚖️",
    label: "Cabinet d'avocat",
    color: "#6366f1",
    template: {
      name: "Cabinet Maître [Votre nom]",
      sector: "Juridique",
      description: "Cabinet d'avocats, conseil et défense, droit civil, droit du travail, droit des affaires.",
      services: "Consultations juridiques, contentieux, négociation, rédaction d'actes, accompagnement entreprises.",
      hours: "Lun-Ven 9h-19h, sur rendez-vous",
      tone: "formel",
    },
    faqs: [
      { question: "Comment prendre rendez-vous ?", answer: "Par téléphone du lundi au vendredi de 9h à 19h. Délai habituel : 5 à 7 jours pour une première consultation." },
      { question: "Quels sont vos tarifs ?", answer: "Première consultation 80 €, durée 1h. Pour un dossier complet, devis personnalisé après analyse." },
      { question: "Quels domaines traitez-vous ?", answer: "Droit civil, droit du travail (côté salarié et employeur), droit des affaires, baux commerciaux, droit de la consommation." },
      { question: "Acceptez-vous l'aide juridictionnelle ?", answer: "Oui, nous acceptons l'aide juridictionnelle totale et partielle. Apportez votre attestation." },
      { question: "Faites-vous des consultations en ligne ?", answer: "Oui, consultations par visio (Google Meet ou Zoom) au même tarif qu'en cabinet, sur rendez-vous." },
      { question: "Combien de temps prend une procédure ?", answer: "Très variable selon la complexité. À titre indicatif : médiation 1-3 mois, procédure prud'homale 12-18 mois, procédure civile 18-24 mois." },
    ],
  },
];

export const BLANK_TEMPLATE = {
  id: "blank",
  icon: "✨",
  label: "Partir d'une page vierge",
  color: "var(--text-dim)",
  template: {
    name: "",
    sector: "Autre",
    description: "",
    services: "",
    hours: "",
    tone: "chaleureux",
  },
  faqs: [{ question: "", answer: "" }],
};
